<?xml version="1.0"?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
  <!--xacro:include
  filename="$(find robot_description)/urdf/lidar.urdf.xacro" /-->
  <!--xacro:include
  filename="$(find robot_description)/urdf/depth.urdf.xacro" /-->

  <xacro:property name="chassis_length" value="0.335" />
  <xacro:property name="chassis_width" value="0.265" />
  <xacro:property name="chassis_height" value="0.138" />
  <xacro:property name="chassis_radius" value="${chassis_width / 2}" />
  <xacro:property name="wheel_radius" value="${chassis_height * 1.3 / 2}" />
  <xacro:property name="wheel_thickness" value="0.06" />
  <xacro:property name="wheel_mass" value="0.05" />
  <xacro:property name="wheel_offset_x" value="${chassis_length / 2 + 0.2 * chassis_length}" />
  <xacro:property name="wheel_offset_y" value="${chassis_width / 2 + wheel_thickness / 2}" />
  <xacro:property name="wheel_offset_z" value="${chassis_height / 2.0}" />
  <xacro:property name="caster_wheel_radius" value="0.03" />
  <xacro:property name="caster_wheel_mass" value="0.01" />
  <xacro:property name="caster_wheel_offset_x" value="0.075" />
  <xacro:property name="caster_wheel_offset_z"
    value="${wheel_offset_z - wheel_radius + caster_wheel_radius}" />
  <xacro:property name="mass" value="1.0" />

  <xacro:property name="antenna_radius" value="0.025" />
  <xacro:property name="antenna_length" value="0.15" />
  <xacro:property name="antenna_mass" value="0.01" />
  <xacro:property name="antenna_color" value="gray" />

  <!-- Координаты установки антенны относительно корпуса -->
  <xacro:property name="antenna_x" value="${chassis_length / 2}" />
  <xacro:property name="antenna_y" value="0" />
  <xacro:property name="antenna_z" value="${chassis_height}" />

  <xacro:property name="laser_radius" value="0.05" />
  <xacro:property name="laser_length" value="0.04" />

  <xacro:property name="depth_cam_radius" value="0.02" />
  <xacro:property name="depth_cam_length" value="0.04" />

  <material name="white">
    <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
    <color rgba="0.98 0.7 0.53 0.95" />
  </material>

  <material name="blue">
    <color rgba="0 0 1 1" />
  </material>

  <material name="black">
    <color rgba="0 0 0 1" />
  </material>

  <material name="red">
    <color rgba="1 0 0 1" />
  </material>

  <material name="gray">
    <color rgba="0.5 0.5 0.5 1" />
  </material>

  <link name="base_link">
  </link>

  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_footprint" />
    <origin xyz="0 0 -${chassis_height}" rpy="0 0 0" />
  </joint>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="chassis" />
    <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}" />
  </joint>

  <link name='chassis'>
    <inertial>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0" />
      <mass value="${mass}" />
      <inertia ixx="${(1/12) * mass * (3*chassis_radius*chassis_radius + chassis_height*chassis_height)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * mass * (3*chassis_radius*chassis_radius + chassis_height*chassis_height)}"
        iyz="0.0"
        izz="${(1/2) * mass * chassis_radius*chassis_radius}" />
    </inertial>
    <visual>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
      <geometry>
        <cylinder radius="${chassis_radius}" length="${chassis_height}" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
      <geometry>
        <cylinder radius="${chassis_radius}" length="${chassis_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel" />
    <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <inertia
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
    </inertial>
  </link>

  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel" />
    <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1" />
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <inertia
        ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
        iyz="0.0"
        izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
    </inertial>
  </link>

  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis" />
    <child link="caster_wheel" />
    <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}" />
  </joint>


  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${caster_wheel_mass}" />
      <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}"
        ixy="0.0" ixz="0.0"
        iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
        izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
    </inertial>
  </link>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001" />
    <mu2 value="0.001" />
  </gazebo>

  <!-- Антенна (центральная) -->
  <link name="antenna">
    <inertial>
      <origin xyz="0 0 ${antenna_length/2}" rpy="0 0 0" />
      <mass value="${antenna_mass}" />
      <inertia
        ixx="${(1/12) * antenna_mass * (3*antenna_radius*antenna_radius + antenna_length*antenna_length)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * antenna_mass * (3*antenna_radius*antenna_radius + antenna_length*antenna_length)}"
        iyz="0.0"
        izz="${(1/2) * antenna_mass * antenna_radius*antenna_radius}" />
    </inertial>

    <visual>
      <origin xyz="0 0 ${antenna_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${antenna_radius}" length="${antenna_length}" />
      </geometry>
      <material name="${antenna_color}" />
    </visual>

    <collision>
      <origin xyz="0 0 ${antenna_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${antenna_radius}" length="${antenna_length}" />
      </geometry>
    </collision>
  </link>

  <joint name="antenna_joint" type="fixed">
    <parent link="chassis" />
    <child link="antenna" />
    <origin xyz="${antenna_x} ${antenna_y} ${antenna_z}" rpy="0 0 0" />
  </joint>

  <!-- Gazebo материал для антенны -->
  <gazebo reference="antenna">
    <material>Gazebo/Gray</material>
  </gazebo>

  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1" />
      <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="chassis" />
    <child link="laser_frame" />
    <origin xyz="${chassis_length} 0 ${chassis_height/2}" rpy="0 0 0" />
  </joint>

  <gazebo reference="laser_frame">
    <sensor name='laser_frame' type='gpu_lidar'>
      <topic>
        scan</topic>
      <!-- <gz_frame_id>laser_frame</gz_frame_id> -->
      <pose relative_to='laser_frame'>0 0 0 0 0 0</pose>
      <update_rate>
        5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>50</samples>
            <resolution>1</resolution>
            <min_angle>-1.396263</min_angle>
            <max_angle>1.396263</max_angle>
          </horizontal>
          <vertical>
            <samples>20</samples>
            <resolution>1</resolution>
            <min_angle>-0.65</min_angle>
            <max_angle>0.65</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.08</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <always_on>1</always_on>
      <visualize>
        true</visualize>
      <!-- <frame name="laser_frame">laser_frame</frame> -->
    </sensor>
  </gazebo>

  <link name="camera_link">
    <visual>
      <geometry>
        <cylinder radius="${depth_cam_radius}" length="${depth_cam_length}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${depth_cam_radius}" length="${depth_cam_length}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1" />
      <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="chassis" />
    <child link="camera_link" />
    <origin xyz="${chassis_length} 0 ${chassis_height/2 + depth_cam_radius*2.01}"
      rpy="0 0 0" />
  </joint>

  <gazebo reference="camera_link">
    <sensor name="depth_camera" type="depth">
      <!-- <gz_frame_id>robot_depth_camera_stop/camera_link</gz_frame_id> -->
      <update_rate>6</update_rate>
      <always_on>1</always_on>
      <camera>
        <horizontal_fov>1.51843645</horizontal_fov>
        <image>
          <width>848</width>
          <height>480</height>
          <format>R_FLOAT32</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>10</far>
        </clip>
        <lens>
          <intrinsics>
            <fx>421.61578369140625</fx>
            <fy>421.61578369140625</fy>
            <cx>422.2854309082031</cx>
            <cy>236.57237243652344</cy>
            <s>0</s>
          </intrinsics>
        </lens>
      </camera>
      <point_cloud_topic>/robot/points</point_cloud_topic>
    </sensor>
  </gazebo>

</robot>


