<?xml version="1.0"?>
<robot name="diff_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- Robot Dimensions -->
  <xacro:property name="base_radius" value="0.5" />
  <xacro:property name="base_height" value="1.0" />
  <xacro:property name="base_mass" value="50.0" />
  
  <xacro:property name="wheel_radius" value="0.3" />
  <xacro:property name="wheel_length" value="0.2" />
  <xacro:property name="wheel_mass" value="5.0" />
  <xacro:property name="wheel_y_offset" value="0.6" />
  <xacro:property name="wheel_z_offset" value="0.1" />
  
  <xacro:property name="caster_radius" value="0.1" />
  <xacro:property name="caster_mass" value="2.0" />
  <xacro:property name="caster_x_offset" value="0.8" />
  <xacro:property name="caster_z_offset" value="0.1" />
  
  <xacro:property name="tower_height" value="0.8" />
  <xacro:property name="tower_radius" value="0.1" />
  <xacro:property name="tower_mass" value="3.0" />

  <!-- Colors -->
  <xacro:property name="blue_color" value="0.0 0.0 0.8 1.0" />
  <xacro:property name="black_color" value="0.0 0.0 0.0 1.0" />
  <xacro:property name="gray_color" value="0.7 0.7 0.7 1.0" />

  <!-- Materials -->
  <material name="blue">
    <color rgba="${blue_color}" />
  </material>
  <material name="black">
    <color rgba="${black_color}" />
  </material>
  <material name="gray">
    <color rgba="${gray_color}" />
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="2.5" ixy="0.0" ixz="0.0" iyy="2.5" iyz="0.0" izz="1.5"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <!-- Caster Wheel -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${caster_mass}"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Sensor Tower -->
  <link name="sensor_tower">
    <visual>
      <geometry>
        <cylinder length="${tower_height}" radius="${tower_radius}"/>
      </geometry>
      <material name="gray"/>
      <origin xyz="0 0 ${tower_height/2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${tower_height}" radius="${tower_radius}"/>
      </geometry>
      <origin xyz="0 0 ${tower_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${tower_mass}"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.02"/>
    </inertial>
  </link>

  <!-- Joints -->

  <!-- Left Wheel Joint -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.1 ${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.5"/>
  </joint>

  <!-- Right Wheel Joint -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.1 -${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.5"/>
  </joint>

  <!-- Caster Wheel Joint -->
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_x_offset} 0 ${caster_z_offset}" rpy="0 0 0"/>
  </joint>

  <!-- Sensor Tower Joint -->
  <joint name="sensor_tower_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_tower"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo plugins and extensions -->
  <xacro:include filename="$(find diff_drive_gazebo)/urdf/robot.gazebo.xacro" />

</robot>